version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      - DB_NAME=carwashdb
      - DB_USER=carwashuser
      - DB_PASSWORD=MySecurePass123!  # Пароль к базе данных
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: carwashdb
      POSTGRES_USER: carwashuser
      POSTGRES_PASSWORD: MySecurePass123!  # Пароль к базе данных
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: